apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rb4pt86p6-go
  janus-idp.io/tekton: rb4pt86p6-go
  backstage.io/kubernetes-id: rb4pt86p6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rb4pt86p6-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
