apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rb4pt86p6-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rb4pt86p6-go 
  name: rb4pt86p6-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rb4pt86p6-go 
